---
- name: Comandos de SQL con módulo oracle_sql
  hosts: mycontainer
  become: yes
  gather_facts: false 

  tasks:
    - name: Copiar librería al container
      copy:
        src: libreria-python/
        dest: /libreria-py/

    - name: Cambiar atributos de archivo de instalación
      file:
        path: /libreria-py/
        mode: 0777 
    
    - name: Ejecutar script instalación
      shell: sudo -iu python3.8 /libreria-py/setup.py install

    - name: Comando número uno
      oracle_sql:                               #Se debe clonar todo el repo para que incluya el módulo
        username: "{{ user }}"                  #Ingresar en el playbook o por encuesta/CLI
        password: "{{ password }}"              #Ingresar en el playbook o por encuesta/CLI
        service_name: one.world                 #Cambiar por el nombre del servicio en el container
        sql: 'select username from dba_users'   #Aquí va la sentencia a utilizar